docker_build_deploy_development:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == 'push'
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${CI_DOCKER_USER}" "${CI_DOCKER_TOKEN}" | base64 | tr -d '\n')\"}}}}" > /kaniko/.docker/config.json
    - echo "${CI_JOB_TOKEN}" > /kaniko/CI_JOB_TOKEN
  script:
    - >
      /kaniko/executor \
          --context "${CI_PROJECT_DIR}" \
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile.Kaniko" \
          --cache \
          --cache-repo "docker.io/heigit/ca-${CI_PROJECT_NAME}-cache" \
          --cache-copy-layers \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:devel" \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:staging" \
          --cleanup

docker_build_deploy_release:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${CI_DOCKER_USER}" "${CI_DOCKER_TOKEN}" | base64 | tr -d '\n')\"}}}}" > /kaniko/.docker/config.json
    - echo "${CI_JOB_TOKEN}" > /kaniko/CI_JOB_TOKEN
  script:
    - >
      /kaniko/executor \
          --context "${CI_PROJECT_DIR}" \
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile.Kaniko" \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:${CI_COMMIT_TAG}" \
          --cleanup