[tool.poetry]
name = "api-gateway"
version = "1.0.0"
description = "The api gateway is the main contact point of the climate action architecture und separates the user realm from the backend."
authors = ["Maciej Adamiak <maciej.adamiak@heigit.org>", "Moritz Schott <moritz.schott@heigit.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11.5"
fastapi = "^0.103.1"
websocket = "^0.2.1"
uvicorn = { extras = ["standard"], version = "^0.23.2" }
cachetools = "^5.3.1"
async-cache = "^1.1.1"
climatoology = { git = "ssh://git@gitlab.gistools.geog.uni-heidelberg.de:2022/climate-action/climatoology.git", rev = "3.0.3" }

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
