[tool.poetry]
name = "api-gateway"
version = "2.1.0"
description = "The api gateway is the main contact point of the climate action architecture und separates the user realm from the backend."
authors = ["Maciej Adamiak <maciej.adamiak@heigit.org>", "Moritz Schott <moritz.schott@heigit.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11.5"
fastapi = "^0.111.0"
starlette = "^0.37.2"
websockets = "^12.0"
uvicorn = { extras = ["standard"], version = "^0.30.1"}
async-cache = "^1.1.1"
climatoology = { git = "ssh://git@gitlab.gistools.geog.uni-heidelberg.de:2022/climate-action/climatoology.git", rev = "5.0.0" }
semver = "^3.0.2"
pyyaml = "^6.0.1"
aio-pika = "^9.4.1"
aiormq = "^6.8.0"
pydantic = "^2.7.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
